### ISSUE TITLE
Revised Media Page

### ISSUE THREAD

**Issue by pmasher** [DuxterInc/dd-community-beta#108]
Please revised Media Page so it looks like this:

![new media mock](https://cloud.githubusercontent.com/assets/9327321/4904399/9a4a4288-6447-11e4-977f-48de0ddea2b2.jpg)

**Comment by bradpettigrew** [comment]
could I get the PSD of the revised media page mock you posted back on the 16th?

**Comment by iamjohnp** [comment]
[Here](https://files.zenhub.io/54ad61dba249c87814469d7e) you go @bradpettigrew.

**Comment by bradpettigrew** [comment]
awesome man thanks!

**Comment by bradpettigrew** [comment]
![media page mock merge](https://cloud.githubusercontent.com/assets/9043584/5671383/77653bce-9755-11e4-88f5-ead64ca9ab46.jpg)
