### ISSUE TITLE
Devtracker doesn't link to the exact dev reply in a thread

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/dd-community-beta#140]
Can we change this, please?

**Comment by adamlieb** [comment]
implemented

**Comment by iamisom** [comment]
This doesn't seem to be working for me. Is this pushed to live?

**Comment by iamjohnp** [comment]
This will only affect posts that were created after we pushed. Older posts
will not be affected.

Can you confirm that it's working with newer posts?

**Comment by iamisom** [comment]
New post:  http://prntscr.com/5th68l
Where it takes me:  http://prntscr.com/5th6bj (top of the thread)

**Comment by adamlieb** [comment]
No this wasn't live until a few minutes ago. It was finished friday but not deployed until this morning. This is working correctly now.

**Comment by iamisom** [comment]
I think there's a new bug with it. When I click I_PASS_BUTTER's newest post, I get sent to the URL https://www.dungeondefenders.com/2/forums?comment_id=1096120&topic_id=116631&slug=see-answer, which is just the forum homepage.

**Comment by adamlieb** [comment]
Clear your cache I don't think you'll experience this. This just went live so your cache likely hasn't been busted yet. I can confirm in all browsers. I suspect when you clear your cache it'll work perfectly.

**Comment by iamisom** [comment]
That worked. Thanks!
