### ISSUE TITLE
Request:  Admin page of monthly site user information

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/dd-community-beta#141]
I need the following information in order to determine our success with the community on our site. For each of these, I'll need the information of all three DD sites together and the information for each site separately. I would prefer to have this information on a page on a site that's available to our admins. 

1)  Monthly Active Posters:  The number of users that have made a post on our site at least once in a month. I would love to have a list of users in descending order of most posts to least posts in a given month so I can determine who our posting MVPs are.

2)  Monthly Active Users:  Same as above except these are the users who have logged in for any given month. I need this to determine the ratio of active posters:active users in a given month. 

3)  Total Number of Posts Made This Month

4)  Total Number of Threads Made This Month

5)  Total Number of Admin/Development Team Posts Made This Month (include the admin/dev numbers together as one number)

6)  Total Number of New Registered Users This Month

**Comment by adamlieb** [comment]
done. Dungeondefenders.com/2/analytics

We are going to add an analytics button on the home page for easier access but here is the link for now.
