### ISSUE TITLE
Unable to change player title

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/dd-community-beta#142]
I'm getting a 404 page when I click to save the new title. The user in question is Lanie, and her usergroup is Defense Council 30.

**Comment by adamlieb** [comment]
What title are you trying to give him/her?

**Comment by iamisom** [comment]
Community Wiki Founder. I was just about to edit my post to add that. :)

**Comment by adamlieb** [comment]
I'll check it out, could be too many characters or something

**Comment by iamisom** [comment]
Thanks!

**Comment by iamisom** [comment]
Update:  I was successfully able to change Supernothing's user title to Community Wiki Lead Editor. I don't think that has to do with the length of the title but rather the usergroup of the person in question.

**Comment by AnthonyKinson** [comment]
Custom Titles are limited to 255 characters and you are well within that. Looking into this further now.

**Comment by adamlieb** [comment]
I really dont know what this issue was. Lanie does have the title you changed it to. Not sure if you've since done this successfully, since first reporting. But I don't see any issue with this. Did this "Just work" at some point? Let me know if you have any issues changing anyone elses title, but right now it APPEARS there is no issue/bug here.

**Comment by iamisom** [comment]
Strange. I haven't touched it since I reported it.

Very weird.

**Comment by iamisom** [comment]
Update that's tied to this:  Did we change anything with Lanie's account? She sent me this message today:

"All my posts are hidden, and I have no permissions to even view topics. I had to log out to see stuff."

**Comment by iamisom** [comment]
This issue also seems to have fixed itself. Closing.

**Comment by iamisom** [comment]
I just logged in, the top right is asking for me to log in.  On the same screen I can see DC areas.  I can also post, but the edit options are removed.
[11:30:50 AM] Lanie Rubyss: I was calling this the "half logged" bug.
[11:32:06 AM] Lanie Rubyss: Also prevents access to reading personal messages...
[11:33:18 AM] Lanie Rubyss: In this state, I can't log out, and pushing the login button, even logging in again, changes nothing. Technical analysis, its probably a bug regarding client side scripting.  I might be able to temp fix it again if I wipe related cookies.  Any client side permissions think I'm not logged in, but the server is treating me as logged in.

**Comment by adamlieb** [comment]
Can you ask them to clear their cache? Then log in/out or out/in depending on their state. This should fix everything, if not let me know and I can dig in further

**Comment by iamisom** [comment]
Will do.

**Comment by iamisom** [comment]
From Lanie:  "Yeah, deleting all cookies for the dungeondefenders domain let me try to login again.  Working normal again for now. But the scripts need to stop breaking the cookies..."

Closing this, but there might be some other issue here.
