### ISSUE TITLE
Analytics Page Changes

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/dd-community-beta#143]
First of all, thank you very much for the Analytics page! It's almost exactly what I need. 

There are two changes to make it perfect for my needs:

1)  A dropdown menu at the top of the page that allows me to select the month and the year for the data (i.e. January 2015).

2)  All data should be tracked on a month-to-month basis (i.e. Jan 1 to Jan 31, 2015; Feb 1 to Feb 28, 2015) and not by "the last 30 days." I need to be able to track my progress month-to-month.

And finally, do we happen to have the metrics for November and December 2014? I know that we lost most of our data on from Oct/Nov, but I'd like to have that if we have it.

**Comment by adamlieb** [comment]
Can do all of this except for "active users" by month. There is no way to see "last month how many people were active." Because we allow people to stay logged in, logins/month is a crappy metric as well. Your best bet for visitor data would be Google Analytics. The "active users" stat will continue to be a rolling 30 days, the rest we can do in monthly slices. 

We can definitely have them go back in time as long as we have data for.

**Comment by iamisom** [comment]
Yeah, I can probably use uniques from Google Analytics, but that's making an assumption that those uniques are also registered members. Is it possible to take a snapshot on the last day of the month? Even if it's not entirely accurate (some months have fewer than 30 days, so it might capture some data from the previous month), it'd be helpful.

**Comment by adamlieb** [comment]
Not really an easy thing to do. If that is a stat you care about, best thing to do would just be to login at the end of the month and take that stat down yourself.

**Comment by iamisom** [comment]
Fair enough!

**Comment by adamlieb** [comment]
This is all done, just waiting to go live.

**Comment by iamisom** [comment]
Do we have any blockers on pushing this live?

**Comment by adamlieb** [comment]
Just waiting on implementing one more thing. Once that is implemented we can push them both live. Just dont want to push a half-complete feature upgrade.

**Comment by iamisom** [comment]
Sounds good.

**Comment by adamlieb** [comment]
implemented & live

**Comment by iamisom** [comment]
Quick question:  Does this also take into account comments made on blogs?

**Comment by rsyvarth** [comment]
Yes
