### ISSUE TITLE
Notification bug

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/dd-community-beta#144]
I have "when someone comments on a thread I track" off, and it's been off for at least two months, but I still receive notifications about this.

Settings:  http://prntscr.com/5snlha
Notifications:  http://prntscr.com/5snljp

**Comment by adamlieb** [comment]
Oh boy are you going to feel like a silly goose. 

http://ss.imjp.me/20150115103458.png

Top two words on that screenshot. EMAIL ME! You aren't getting emails for these notifications are you?

There isn't a way to turn off on-site notifications. 

Currently this is working as intended (unless you ARE getting emails about these things) please confirm

**Comment by iamjohnp** [comment]
@iamisom i'll note too that you can untrack threads you start or comment on if you're getting too many notifications. that would allow you some micro-management in case you *did* want replies to *some* threads you track (as opposed to all or none).

**Comment by iamisom** [comment]
I AM A SILLY GOOSE. I'm not getting the emails. Working as intended. I'll untrack myself from those threads. Carry on!
