### ISSUE TITLE
Posts with quotes are getting pushed into the reply/like bar

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/dd-community-beta#146]
http://prntscr.com/5up3rs
http://prntscr.com/5up3ts

**Comment by Xspirits** [comment]
I wasn't able to reproduce on staging, can you please provide the link where this is occurring please @iamisom?

**Comment by kaiheilos** [comment]
https://www.dungeondefenders.com/2/topic/116644/

**Comment by iamjohnp** [comment]
A fix for this has been deployed to production. Let us know if you see any related issues.
